routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
|
|  Dev: D.K.
|  Date start: 09.03.2023
|  Date finish: 10.03.2023
|
|
*/





Auth::routes();

Route::redirect('/register', '/login');
Route::redirect('/home', '/admin');



Route::group(['namespace' => 'App\Http\Controllers\Frontend'], function() {
    Route::get('/', 'AboutController@index')->name('about');
    Route::get('/books', 'BooksController@index')->name('books');
    Route::get('/book/{id}', 'BooksController@single')->name('book-single');
    Route::get('/musings', 'MusingsController@index')->name('musings');
});




Route::group(['middleware'=> ['auth', 'admin'], 'prefix' => '/admin', 'namespace' => 'App\Http\Controllers\Backend'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('/about/slider', 'AboutSliderController');
    Route::resource('/about/section', 'AboutSectionController');
    Route::resource('/book', 'BooksController');
    Route::resource('/musing', 'MusingController');
    Route::resource('/user', 'UserController');
});

app/Http/Controllers/Frontend/AboutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\AboutSection;
use App\Models\AboutSlider;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class AboutController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $sliders = AboutSlider::all();
        $sections = AboutSection::query()->where('status', 1)->get();
        return view('frontend.about', compact('sliders', 'sections'));
    }

}

resources/views/backend/dashboard/about/slider/create.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Create</title>
@endsection

@section('css')

@endsection



@section('dashboard')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Create</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>


    <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">

                    <div class="col-md-12">
                        <div class="card card-default">
                            <div class="card-header">
                                <h3 class="card-title">Slider</h3>
                            </div>
                            <form action="{{route('slider.store')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="card-body row">
                                    <div class="form-group col-12">
                                        <div class="form-group col-12">
                                            <label for="exampleInputFile">Images</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file"  class="custom-file-input" name="image" id="imgfilesOne">
                                                    <label class="custom-file-label" for="imgfilesOne">Choose file</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="img-view-one">

                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-success">Save</button>
                                </div>
                            </form>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
            </div>
        </section>
    <!-- /.content -->
</div>
@endsection

@section('js')
    <script>
        $(document).on('change', '.custom-file-input', function () {
            let name = $(this).val().replace(/.*(\/|\\)/, '')
            $(this).closest('.custom-file').find('.custom-file-label').html(name)

            $(this).closest('.custom-file').closest('.input-group').closest('.form-group').find('.custom-audio').html(`
                <br>
                <audio controls>
                    <source src="${window.URL.createObjectURL(this.files[0])}" type="audio/ogg">
                    <source src="${window.URL.createObjectURL(this.files[0])}" type="audio/mpeg">
                </audio>
            `)
        })
    </script>

@endsection

resources/views/backend/dashboard/about/slider/edit.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Edit</title>
@endsection

@section('css')
@endsection

@section('dashboard')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-12">
                    <div class="card card-default">
                        <div class="card-header">
                            <h3 class="card-title">Slider</h3>
                        </div>
                        <form action="{{route('slider.update', $slider->id)}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')
                            <div class="card-body row">
                                <div class="form-group col-12">
                                    <div class="form-group col-12">
                                        <label for="exampleInputFile">First Images</label>
                                        <div class="input-group">
                                            <div class="custom-file">
                                                <input type="file"  class="custom-file-input" name="image" id="imgfilesOne">
                                                <label class="custom-file-label" for="imgfilesOne">Choose file</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="img-view-one">

                                    </div>
                                    <div>
                                        <img src="{{asset($slider->path)}}" alt="" style="width: 30%;">
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/about/slider/index.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Slider</title>
@endsection

@section('css')

    <style>
        .custom-scroll{
            display: block;
            height: 100px !important;
            overflow-y: scroll;
        }
    </style>
@endsection



@section('dashboard')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Slider</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                            <li class="breadcrumb-item active">About slider</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div>
                                <a href="{{route('slider.create')}}" class="btn btn-success" style="float: right; margin: 15px">Create</a>
                            </div>
                        <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Image</th>
                                        <th>Access</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($sliders as $slider)
                                            <tr>
                                                <td>{{$slider->id}}</td>
                                                <td style="width: 10%;"><img src="{{asset($slider->path)}}" alt="" style="width: 100%;"></td>
                                                <td>
                                                    <div class="d-flex">
                                                        <a style="padding: 0px 5px;margin: 0px 8px;" href="{{ route("slider.edit", $slider->id) }}" class="btn btn-primary edit-access"><i  class="fas fa-edit" ></i></a>
                                                        <form method="POST" action="{{ route("slider.destroy" , $slider->id) }}">
                                                            @csrf
                                                            @method('DELETE')
                                                            <a href="javascript:;" onclick="return confirm('Are you sure you want to delete this item?');">
                                                                <button type="submit" style="padding: 0px 5px;" class="ml-2 btn btn-danger" >
                                                                    <i class="fa fa-trash"></i>
                                                                </button>
                                                            </a>
                                                        </form>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                            <div style="margin: 0 auto">
                                {{ $sliders->links('pagination::bootstrap-4') }}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('js')


@endsection