routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
|
|  Dev: D.K.
|  Date start: 09.03.2023
|  Date finish: 10.03.2023
|
|
*/





Auth::routes();

Route::redirect('/register', '/login');
Route::redirect('/home', '/admin');



Route::group(['namespace' => 'App\Http\Controllers\Frontend'], function() {
    Route::get('/', 'AboutController@index')->name('about');
    Route::get('/books', 'BooksController@index')->name('books');
    Route::get('/book/{id}', 'BooksController@single')->name('book-single');
    Route::get('/musings', 'MusingsController@index')->name('musings');
});




Route::group(['middleware'=> ['auth', 'admin'], 'prefix' => '/admin', 'namespace' => 'App\Http\Controllers\Backend'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('/about/slider', 'AboutSliderController');
    Route::resource('/about/section', 'AboutSectionController');
    Route::resource('/book', 'BooksController');
    Route::resource('/musing', 'MusingController');
    Route::resource('/user', 'UserController');
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    protected $table = 'books';

    protected $fillable =[
        'title',
        'sub_description',
        'description',
        'author',
        'path',
        'status',
    ];

}

app/Http/Controllers/Backend/BooksController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Hellper\Hellper;
use App\Models\Book;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class BooksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $books = Book::query()->paginate(10);
        return view('backend.dashboard.book.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('backend.dashboard.book.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        try {
            DB::beginTransaction();

            $path = storage_path('app' . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR . 'book' . DIRECTORY_SEPARATOR);
            $name =  Hellper::upload($request->image, $path);
            $image = "/storage/book/" . $name;

            $book = Book::create([
                'path' =>$image,
                'title' =>$request->title,
                'author' =>$request->author,
                'sub_description' =>$request->sub_description,
                'description' =>$request->description,
                'status' => isset($request->status) ? 1 : 0,
            ]);

            DB::commit();
            return redirect()->route('book.index')->with('message', 'Successfully');
        } catch (\Throwable $e) {
            DB::rollBack();
            return redirect()->back()->with('error', 'error');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit($id)
    {
        $book = Book::findOrFail($id);
        return view('backend.dashboard.book.edit', compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        try {
            DB::beginTransaction();

            $book = Book::findOrFail($id);

            if (isset($request->image)){
                $PathForDelete = str_replace('/storage', '', $book->path);
                Storage::delete('/public' . $PathForDelete);
                $path = storage_path('app' . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR . 'book' . DIRECTORY_SEPARATOR);
                $name =  Hellper::upload($request->image, $path);
                $image = "/storage/book/" . $name;
                $book->path = $image;
            }

            $book->title = $request->title;
            $book->author = $request->author;
            $book->sub_description = $request->sub_description;
            $book->description = $request->description;
            $book->status = isset($request->status) ? 1 : 0;

            $book->save();


            DB::commit();
            return redirect()->route('book.index')->with('message', 'Successfully');
        } catch (\Throwable $e) {
            DB::rollBack();
            return redirect()->back()->with('error', 'error');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $book = Book::findOrFail($id);
        $PathForDelete = str_replace('/storage', '', $book->path);
        Storage::delete('/public' . $PathForDelete);
        $book->delete();
        return redirect()->route('book.index')->with('message', 'Successfully');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        return view('backend.dashboard.dashboard');
    }
}

app/Http/Controllers/Frontend/BooksController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\Book;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class BooksController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $books = Book::all();
        return view('frontend.books', compact('books'));
    }


    public function single($id)
    {
        $book = Book::findOrFail($id);
        $books = Book::all();
        return view('frontend.single-book', compact('book', 'books'));
    }
}

resources/views/backend/dashboard/book/create.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Create</title>
@endsection

@section('css')

@endsection



@section('dashboard')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Create</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                        <li class="breadcrumb-item active">Create</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>


    <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">

                    <div class="col-md-12">
                        <div class="card card-default">
                            <div class="card-header">
                                <h3 class="card-title">Book</h3>
                            </div>
                            <form action="{{route('book.store')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="card-body row">
                                    <div class="card-body row">
                                        <div class="form-group col-12">
                                            <div class="form-group col-12">
                                                <label for="exampleInputFile">First Images</label>
                                                <div class="input-group">
                                                    <div class="custom-file">
                                                        <input type="file"  class="custom-file-input" name="image" id="imgfilesOne">
                                                        <label class="custom-file-label" for="imgfilesOne">Choose file</label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div id="img-view-one">

                                            </div>
                                        </div>
                                        <div class="form-group col-6">
                                            <label>Title</label>
                                            <input class="form-control" type="text" name="title" placeholder="Slug title" value="{{ old('title') }}">
                                        </div>
                                        <div class="form-group col-6">
                                            <label>Author</label>
                                            <input class="form-control" type="text" name="author" placeholder="Slug author"  value="{{ old('author') }}">
                                        </div>
                                        <div class="form-group col-12">
                                            <label>Sub description</label>
                                            <textarea class="summernote" name="sub_description">{{ old('sub_description') }}</textarea>
                                        </div>
                                        <div class="form-group col-12">
                                            <label>Description</label>
                                            <textarea class="summernote" name="description">{{ old('description') }}</textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>View</label>
                                            <input class="form-control" type="checkbox" name="status" checked>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn btn-success">Save</button>
                                </div>
                            </form>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
            </div>
        </section>
    <!-- /.content -->
</div>
@endsection

@section('js')
    <script>
        $(document).on('change', '.custom-file-input', function () {
            let name = $(this).val().replace(/.*(\/|\\)/, '')
            $(this).closest('.custom-file').find('.custom-file-label').html(name)

            $(this).closest('.custom-file').closest('.input-group').closest('.form-group').find('.custom-audio').html(`
                <br>
                <audio controls>
                    <source src="${window.URL.createObjectURL(this.files[0])}" type="audio/ogg">
                    <source src="${window.URL.createObjectURL(this.files[0])}" type="audio/mpeg">
                </audio>
            `)
        })
    </script>

@endsection

resources/views/backend/dashboard/book/edit.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Edit</title>
@endsection

@section('css')
@endsection

@section('dashboard')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-12">
                    <div class="card card-default">
                        <div class="card-header">
                            <h3 class="card-title">Slider</h3>
                        </div>
                        <form action="{{route('book.update', $book->id)}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')
                            <div class="card-body row">
                                <div class="card-body row">
                                    <div class="form-group col-12">
                                        <div class="form-group col-12">
                                            <label for="exampleInputFile">First Images</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file"  class="custom-file-input" name="image" id="imgfilesOne">
                                                    <label class="custom-file-label" for="imgfilesOne">Choose file</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="img-view-one">

                                        </div>
                                        <div>
                                            <img src="{{asset($book->path)}}" alt="" style="width: 30%;">
                                        </div>
                                    </div>
                                    <div class="form-group col-6">
                                        <label>Title</label>
                                        <input class="form-control" type="text" name="title" placeholder="Slug title" value="{{ $book->title }}">
                                    </div>
                                    <div class="form-group col-6">
                                        <label>Author</label>
                                        <input class="form-control" type="text" name="author" placeholder="Slug author"  value="{{$book->author }}">
                                    </div>
                                    <div class="form-group col-12">
                                        <label>Sub description</label>
                                        <textarea class="summernote" name="sub_description">{{ $book->sub_description }}</textarea>
                                    </div>
                                    <div class="form-group col-12">
                                        <label>Description</label>
                                        <textarea class="summernote" name="description">{{ $book->description }}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label>View</label>
                                        <input class="form-control" type="checkbox" name="status" @if($book->status) checked @endif>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/book/index.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Books</title>
@endsection

@section('css')

    <style>
        .custom-scroll{
            display: block;
            height: 100px !important;
            overflow-y: scroll;
        }
    </style>
@endsection



@section('dashboard')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Books</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                            <li class="breadcrumb-item active">Books</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div>
                                <a href="{{route('book.create')}}" class="btn btn-success" style="float: right; margin: 15px">Create</a>
                            </div>
                        <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Image</th>
                                        <th>Title</th>
                                        <th>Author</th>
                                        <th>Sub description</th>
                                        <th>Description</th>
                                        <th>View</th>
                                        <th>Access</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($books as $book)
                                            <tr>
                                                <td>{{$book->id}}</td>
                                                <td style="width: 10%;"><img src="{{asset($book->path)}}" alt="" style="width: 100%;"></td>
                                                <td>{{$book->title}}</td>
                                                <td>{{$book->author}}</td>
                                                <td>{!! $book->sub_description !!}</td>
                                                <td>{!! $book->description !!}</td>
                                                <td>{{$book->status ? 'View' : 'Hidden'}}</td>
                                                <td>
                                                    <div class="d-flex">
                                                        <a style="padding: 0px 5px;margin: 0px 8px;" href="{{ route("book.edit", $book->id) }}" class="btn btn-primary edit-access"><i  class="fas fa-edit" ></i></a>
                                                        <form method="POST" action="{{ route("book.destroy" , $book->id) }}">
                                                            @csrf
                                                            @method('DELETE')
                                                            <a href="javascript:;" onclick="return confirm('Are you sure you want to delete this item?');">
                                                                <button type="submit" style="padding: 0px 5px;" class="ml-2 btn btn-danger" >
                                                                    <i class="fa fa-trash"></i>
                                                                </button>
                                                            </a>
                                                        </form>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                            <div style="margin: 0 auto">
                                {{ $books->links('pagination::bootstrap-4') }}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('js')


@endsection