routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
|
|  Dev: D.K.
|  Date start: 09.03.2023
|  Date finish: 10.03.2023
|
|
*/





Auth::routes();

Route::redirect('/register', '/login');
Route::redirect('/home', '/admin');



Route::group(['namespace' => 'App\Http\Controllers\Frontend'], function() {
    Route::get('/', 'AboutController@index')->name('about');
    Route::get('/books', 'BooksController@index')->name('books');
    Route::get('/book/{id}', 'BooksController@single')->name('book-single');
    Route::get('/musings', 'MusingsController@index')->name('musings');
});




Route::group(['middleware'=> ['auth', 'admin'], 'prefix' => '/admin', 'namespace' => 'App\Http\Controllers\Backend'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('/about/slider', 'AboutSliderController');
    Route::resource('/about/section', 'AboutSectionController');
    Route::resource('/book', 'BooksController');
    Route::resource('/musing', 'MusingController');
    Route::resource('/user', 'UserController');
});

app/Http/Controllers/Frontend/AboutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\AboutSection;
use App\Models\AboutSlider;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class AboutController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $sliders = AboutSlider::all();
        $sections = AboutSection::query()->where('status', 1)->get();
        return view('frontend.about', compact('sliders', 'sections'));
    }

}

resources/views/backend/dashboard/about/section/edit.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Edit</title>
@endsection

@section('css')
@endsection

@section('dashboard')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-12">
                    <div class="card card-default">
                        <div class="card-header">
                            <h3 class="card-title">Section</h3>
                        </div>
                        <form action="{{route('section.update', $section->id)}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')
                            <div class="card-body row">
                                @if(isset($section->path))
                                    <div class="form-group col-12">
                                        <div class="form-group col-12">
                                            <label for="exampleInputFile">First Images</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file"  class="custom-file-input" name="image" id="imgfilesOne">
                                                    <label class="custom-file-label" for="imgfilesOne">Choose file</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div id="img-view-one">

                                        </div>
                                        <div>
                                            <img src="{{asset($section->path)}}" alt="" style="width: 30%;">
                                        </div>
                                    </div>
                                @endif
                                <div class="form-group col-6">
                                    <label>Title</label>
                                    <input class="form-control" type="text" name="title" placeholder="Slug title" value="{{ $section->title }}">
                                </div>
                                @if(isset($section->sub_title))
                                    <div class="form-group col-6">
                                        <label>Sub Title</label>
                                        <input class="form-control" type="text" name="description" placeholder="Slug title"  value="{{ $section->sub_title }}">
                                    </div>
                                @endif
                                <div class="form-group">
                                    <label>View</label>
                                    <input class="form-control" type="checkbox" name="status" @if($section) checked @endif>
                                </div>
                                <div class="form-group col-12">
                                    <label>Description</label>
                                    <textarea class="summernote" name="description">{{ $section->description }}</textarea>
                                </div>

                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

@section('js')

@endsection

resources/views/backend/dashboard/about/section/index.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Sections</title>
@endsection

@section('css')

    <style>
        .custom-scroll{
            display: block;
            height: 100px !important;
            overflow-y: scroll;
        }
    </style>
@endsection



@section('dashboard')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Sections</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                            <li class="breadcrumb-item active">About Sections</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                        <!-- /.card-header -->
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Image</th>
                                        <th>Title</th>
                                        <th>Sub Title</th>
                                        <th>Description</th>
                                        <th>View</th>
                                        <th>Access</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($sections as $section)
                                            <tr>
                                                <td>{{$section->id}}</td>
                                                <td style="width: 10%;"><img src="{{asset($section->path)}}" alt="" style="width: 100%;"></td>
                                                <td>{{$section->title}}</td>
                                                <td>{{$section->sub_title}}</td>
                                                <td>{!! $section->description !!}</td>
                                                <td>{{ $section->status ? 'View' : 'Hidden' }}</td>

                                                <td>
                                                    <div class="d-flex">
                                                        <a style="padding: 0px 5px;margin: 0px 8px;" href="{{ route("section.edit", $section->id) }}" class="btn btn-primary edit-access"><i  class="fas fa-edit" ></i></a>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                            <div style="margin: 0 auto">
                                {{ $sections->links('pagination::bootstrap-4') }}
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('js')


@endsection