routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
|
|  Dev: D.K.
|  Date start: 09.03.2023
|  Date finish: 10.03.2023
|
|
*/





Auth::routes();

Route::redirect('/register', '/login');
Route::redirect('/home', '/admin');



Route::group(['namespace' => 'App\Http\Controllers\Frontend'], function() {
    Route::get('/', 'AboutController@index')->name('about');
    Route::get('/books', 'BooksController@index')->name('books');
    Route::get('/book/{id}', 'BooksController@single')->name('book-single');
    Route::get('/musings', 'MusingsController@index')->name('musings');
});




Route::group(['middleware'=> ['auth', 'admin'], 'prefix' => '/admin', 'namespace' => 'App\Http\Controllers\Backend'], function() {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('/about/slider', 'AboutSliderController');
    Route::resource('/about/section', 'AboutSectionController');
    Route::resource('/book', 'BooksController');
    Route::resource('/musing', 'MusingController');
    Route::resource('/user', 'UserController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        return view('backend.dashboard.dashboard');
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Hellper\Hellper;
use App\Models\Musing;
use App\Models\MusingImage;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('backend.dashboard.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
//        dd($request->all());
        try {
            DB::beginTransaction();

            $user = User::findOrFail($id);
            $user->update([
                'name' => $request->name,
                'instagram' => $request->instagram,
                'email' => $request->email,
                'password' => \Hash::make($request->password),
            ]);


            DB::commit();
            return redirect()->back()->with('message', 'Successfully');
        } catch (\Throwable $e) {
            DB::rollBack();
            return redirect()->back()->with('error', 'error');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/dashboard/user/edit.blade.php
@extends('layouts.dashboard')


@section('title')
    <title>Edit</title>
@endsection

@section('css')
@endsection

@section('dashboard')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-12">
                    <div class="card card-default">
                        <div class="card-header">
                            <h3 class="card-title">Musing</h3>
                        </div>
                        <form action="{{route('user.update', $user->id)}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')
                            <div class="card-body row">
                                <div class="card-body row">
                                    <div class="form-group col-6">
                                        <label>Title</label>
                                        <input class="form-control" type="text" name="name" placeholder="Slug name" value="{{ $user->name }}">
                                    </div>

                                    <div class="form-group col-6">
                                        <label>Sub title</label>
                                        <input class="form-control" type="text" name="email" placeholder="Slug email"  value="{{$user->email }}">
                                    </div>
                                    <div class="form-group col-6">
                                        <label>Sub title</label>
                                        <input class="form-control" type="text" name="password" placeholder="Slug password"  value="">
                                    </div>
                                    <div class="form-group col-6">
                                        <label>Sub title</label>
                                        <input class="form-control" type="text" name="instagram" placeholder="Slug instagram"  value="{{$user->instagram }}">
                                    </div>

                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-success">Save</button>
                            </div>
                        </form>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
</div>
@endsection

@section('js')
    <script>
        $(document).on('change', '.custom-file-input', function () {
            console.log( $(this))
            let name = $(this).val().replace(/.*(\/|\\)/, '')
            $(this).closest('.custom-file').find('.custom-file-label').html(name)

            if(this.files[0].type == 'video/mp4' || this.files[0].type == 'video/ogg'){
                $('#img-view-one').html('')
                $('.custom-video').html(`
                <br>
                <video width="320" height="240" controls>
                  <source src="${window.URL.createObjectURL(this.files[0])}" type="video/mp4">
                  <source src="${window.URL.createObjectURL(this.files[0])}" type="video/ogg">
                Your browser does not support the video tag.
                </video>
            `)
            }else{

            }

        })
    </script>
@endsection